import React from "react";
import Head from "next/head";

function Layout({ title, children }) {
  const styles = {
    wrapper: "bg-gray-300",
    content: "container mx-auto max-w-xl pt-8 min-h-screen",
  };
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.content}>
      {children}
      </main>
    </div>
  );
}

export default Layout;
